documentation
howto
	^ HelpTopic 
		title: 'How To'
		contents: 
'!! ADDING STATES

To add a state click on the appropriate button in the palette, then click on the canvas to add it.
You can continue clicking on the canvas to add continue adding more states.

!! ADDING TRANSITIONS

To add a transition, click on the ''Transition'' in the palette and then click on one of the states --- the initial one. Then click on second state --- the final one.
YOu can continue clicking on states to add more transitions.

!! RENAMING STATES AND TRANSITIONS

To rename a state or a transition simply doubleclick it (with left mouse button), and rename popup will appear.

For simulator purposes, multiple transition events can be separated by commas.

!! REMOVING STATES AND TRANSITIONS

To remove a state or a transition, right click on the object and select ''Remove''. If there are transitions connected to a removed state, they will be also removed.

'